# Generated by Django 6.0.5 on 2026-05-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0003_internalmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalmessage',
            name='message_type',
            field=models.CharField(choices=[('chat', 'Chat'), ('report', 'Report')], default='chat', max_length=10),
        ),
    ]
