# Generated by Django 6.0.5 on 2026-05-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0004_internalmessage_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalmessage',
            name='file_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internalmessage',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
