# Generated by Django 6.0.5 on 2026-10-05 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0011_case_user_set_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='counselling.case'),
        ),
    ]
